sudo:     required  # using VM

language: cpp

os:
  - linux

compiler:
  - gcc

env:
  # список переменных окружения, влияющих на матрицу сборки:
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

matrix:
  exclude:
    # вручную исключим ненужные элементы из матрицы сборки:
    - os:       osx
      compiler: gcc

    - os:  osx
      env: TARGET_CPU=x86 BUILD_CONFIGURATION=Debug

    - os:  osx
      env: TARGET_CPU=x86 BUILD_CONFIGURATION=Release

install:
  # set environment and set dependencies
  - source ci/travis/install-$TRAVIS_OS_NAME.sh

script:
  # test project
  - cd cmake-build-debug
  - cmake ..
  - make
  - ctest --output-on-failure

deploy:
  # release tagged-commits on GitHub Releases:
  provider:     releases
  file:         <package-file>
  skip_cleanup: true
  overwrite:    true

  api_key:
    secure:   <encrypted-github-token>

  on:
    tags:     true